<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.eggy03</groupId>
    <artifactId>nautilus-windows-x86</artifactId>
    <version>1.0.0</version>

    <name>Nautilus</name>
    <description>A Swing based GUI for viewing system information</description>

    <properties>
        <!-- build -->
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Dependency versions -->
        <cimari.version>0.1.0</cimari.version>
        <slf4j.version>2.0.17</slf4j.version>
        <tinylog.version>2.7.0</tinylog.version>
        <flatlaf.version>3.7.1</flatlaf.version>
        <jsvg.version>2.1.0</jsvg.version>
        <lombok.version>1.18.44</lombok.version>
        <commons.lang3.version>3.20.0</commons.lang3.version>
        <commons.io.version>2.21.0</commons.io.version>
        <miglayout.version>11.4.3</miglayout.version>

        <!-- Plugin versions -->
        <maven.compiler.plugin.version>3.15.0</maven.compiler.plugin.version>
        <maven.clean.plugin.version>3.5.0</maven.clean.plugin.version>
        <maven.resources.plugin.version>3.5.0</maven.resources.plugin.version>
        <jpackage.maven.plugin.version>1.7.4</jpackage.maven.plugin.version>
        <jlink.maven.plugin.version>1.2.1</jlink.maven.plugin.version>
        <native-maven-plugin.version>1.1.0</native-maven-plugin.version>
        <exec.maven.plugin.version>3.6.3</exec.maven.plugin.version>

        <!-- Extras -->
        <app.main.class>io.github.eggy03.nautilus.windows.Start</app.main.class>
        <app.fatjar.name>${project.build.finalName}-jar-with-dependencies.jar</app.fatjar.name>
        <app.fatjar.directory>${project.build.directory}/fatjar</app.fatjar.directory>

        <jlink.output.directory>${project.build.directory}/runtime</jlink.output.directory>
        <jpackage.output.directory>${project.build.directory}/output</jpackage.output.directory>

        <project.windows.icon>${project.basedir}/icons/nautilus.ico</project.windows.icon>
        <project.linux.icon>${project.basedir}/icons/nautilus.png</project.linux.icon>
    </properties>

    <dependencies>
        <!-- :) -->
        <dependency>
            <groupId>io.github.eggy03</groupId>
            <artifactId>cimari</artifactId>
            <version>${cimari.version}</version>
        </dependency>

        <!-- UI -->
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>${flatlaf.version}</version>
        </dependency>

        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf-extras</artifactId>
            <version>${flatlaf.version}</version>
        </dependency>

        <dependency>
            <groupId>com.miglayout</groupId>
            <artifactId>miglayout-swing</artifactId>
            <version>${miglayout.version}</version>
        </dependency>

        <dependency>
            <groupId>com.github.weisj</groupId>
            <artifactId>jsvg</artifactId>
            <version>${jsvg.version}</version>
            <scope>runtime</scope>
        </dependency>

        <!-- Logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.tinylog</groupId>
            <artifactId>slf4j-tinylog</artifactId>
            <version>${tinylog.version}</version>
        </dependency>

        <dependency>
            <groupId>org.tinylog</groupId>
            <artifactId>tinylog-impl</artifactId>
            <version>${tinylog.version}</version>
        </dependency>

        <!-- Utility -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons.lang3.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons.io.version}</version>
        </dependency>

        <!-- Annotation -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>${maven.clean.plugin.version}</version>
            </plugin>

            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <mainClass>${app.main.class}</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <profiles>

        <!--JVM Builds With Jpackage-->
        <profile>
            <id>dist</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-resources-plugin</artifactId>
                        <version>${maven.resources.plugin.version}</version>
                        <executions>
                            <execution>
                                <id>prepare-jpackage-input</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${app.fatjar.directory}</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>${project.build.directory}</directory>
                                            <includes>
                                                <include>${app.fatjar.name}</include>
                                            </includes>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jlink-maven-plugin</artifactId>
                        <version>${jlink.maven.plugin.version}</version>

                        <executions>
                            <execution>
                                <id>jlink-runtime</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jlink</goal>
                                </goals>
                            </execution>
                        </executions>

                        <configuration>
                            <output>${jlink.output.directory}</output>

                            <addModules>
                                <addModule>java.base</addModule>
                                <addModule>java.desktop</addModule>
                                <addModule>java.logging</addModule>
                                <addModule>java.xml</addModule>
                                <addModule>java.prefs</addModule>
                                <addModule>java.datatransfer</addModule>
                                <addModule>java.management</addModule>
                                <addModule>java.naming</addModule>
                                <addModule>jdk.unsupported</addModule>
                            </addModules>

                            <stripDebug>false</stripDebug>
                            <noHeaderFiles>true</noHeaderFiles>
                            <noManPages>true</noManPages>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>${jpackage.maven.plugin.version}</version>

                        <!-- Base config shared by all OSes -->
                        <configuration>
                            <name>Nautilus</name>
                            <appVersion>${project.version}</appVersion>
                            <vendor>eggy03</vendor>
                            <description>${project.name}</description>

                            <!-- App-image only -->
                            <type>APP_IMAGE</type>

                            <!-- Fat JAR -->
                            <input>${app.fatjar.directory}</input>
                            <mainJar>${app.fatjar.name}</mainJar>
                            <mainClass>${app.main.class}</mainClass>

                            <!-- Custom JRE created by jlink -->
                            <runtimeImage>${jlink.output.directory}</runtimeImage>

                            <!-- Output -->
                            <destination>${jpackage.output.directory}</destination>

                            <!-- JVM opts -->
                            <javaOptions>
                                <option>-Dfile.encoding=UTF-8</option>
                            </javaOptions>

                            <!-- Windows GUI -->
                            <winConsole>false</winConsole>
                        </configuration>

                        <!-- OS-selectable executions -->
                        <executions>

                            <!-- Windows -->
                            <execution>
                                <id>win</id>
                                <configuration>
                                    <icon>${project.windows.icon}</icon>
                                </configuration>
                            </execution>

                            <!-- Linux -->
                            <execution>
                                <id>linux</id>
                                <configuration>
                                    <icon>${project.linux.icon}</icon>
                                </configuration>
                            </execution>

                        </executions>
                    </plugin>

                </plugins>
            </build>
        </profile>
    </profiles>
</project>